In [29]:
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.stats.proportion as prop

In [9]:
rocslow = np.loadtxt('./ROConly/orderingcriteria.dat')
rocfast = np.loadtxt('./ROConly/orderingcriteriafastROC.dat')
comboslow = np.loadtxt('./HPsatANDroc/orderingcriteria.dat')
combofast = np.loadtxt('./HPsatANDroc/orderingcriteriafastcombo.dat')

In [11]:
len(combofast)

100

In [20]:
#to what extent can I treat the first two ordering criteria like a block?
print(np.where(rocslow[:,0] != rocslow[:,1])[0])
print(rocslow[51])
print(np.where(rocfast[:,0] != rocfast[:,1])[0])
print('no deviance')
print(np.where(comboslow[:,0] != comboslow[:,1])[0])
print(comboslow[18])
print(np.where(combofast[:,0] != combofast[:,1])[0])
print(combofast[17])
#one instance of non-equality in three of four data sets

[51]
[0. 1. 1.]
[]
no deviance
[18]
[0. 1. 1.]
[17]
[0. 1. 0.]


In [26]:
#create pooled data
rocfast_cut = rocfast[np.where(rocfast[:,0]!=2)[0]]
len(rocfast_cut)

combofast_cut = combofast[np.where(combofast[:,0]!=2)[0]]
len(combofast_cut)

roc_pool = np.concatenate((rocfast_cut,rocslow))
combo_pool = np.concatenate((combofast_cut,comboslow))

In [38]:
#analyze pooled data
n = 200 # number of evolutions per condition

roc_count_assessable = len(roc_pool)
combo_count_assessable = len(combo_pool)
# print(roc_count_assessable,combo_count_assessable)

roc_count_pyloric = len(np.where(np.sum(roc_pool,axis=1)==3)[0])
combo_count_pyloric = len(np.where(np.sum(combo_pool,axis=1)==3)[0])

roc_count_0 = np.sum(roc_pool[:,0])
combo_count_0 = np.sum(combo_pool[:,0])
roc_count_1 = np.sum(roc_pool[:,1])
combo_count_1 = np.sum(combo_pool[:,1])
roc_count_2 = np.sum(roc_pool[:,2])
combo_count_2 = np.sum(combo_pool[:,2])

# print(roc_count_0,combo_count_0,roc_count_1,combo_count_1,roc_count_2,combo_count_2)

stat,pval0 = prop.proportions_ztest([roc_count_0,combo_count_0],[n,n],0)
print(pval0)

stat,pval1 = prop.proportions_ztest([roc_count_1,combo_count_1],[n,n],0)
print(pval1)

stat,pval2 = prop.proportions_ztest([roc_count_2,combo_count_2],[n,n],0)
print(pval2)

print('pyloric counts:',roc_count_pyloric,combo_count_pyloric)
stat,pvalp = prop.proportions_ztest([roc_count_pyloric,combo_count_pyloric],[n,n],0)
print(pvalp)

0.8135492910287812
0.9071293098656603
0.43933571594215004
pyloric counts: 5 19
0.003203218836972529
