In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
recovery = np.zeros((100,5,121,10))
final_recovery = np.zeros_like(recovery[:,:,:,0])
pyl_recovery = np.zeros((100,5))
for i in range(100):
    for j in range(5):
        # print(np.loadtxt("./Specifically Evolved HP mechanisms/Every Circuit/%s/%s/recoverytest.dat"%(i,j))[:,2:])
        recovery[i,j] = np.loadtxt("./Specifically Evolved HP mechanisms/Every Circuit/%s/%s/recoverytest.dat"%(i,j))[:,2:]
        final_recovery[i,j] = recovery[i,j,:,-1]
        pyl_recovery[i,j] = np.sum(final_recovery[i,j]>=.3)


In [9]:
print(pyl_recovery)

[[121.   0. 121. 121. 121.]
 [ 84. 116. 121. 121. 121.]
 [  0.  26.   0.   0.   0.]
 [121. 121. 121.  70.  74.]
 [116.   0.   0.   0.  62.]
 [121. 113.   0. 121. 121.]
 [ 85.  84.  87.  87.  90.]
 [121. 121. 121. 121. 121.]
 [ 99.  85.  81.  99.  95.]
 [  0.   0.   0.  41.   0.]
 [ 12.  20.   0.   0.   1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.  33.   0.   0.]
 [121. 121.  99.   0.  86.]
 [ 21.  20.   0.   0.   0.]
 [ 73.  70.  78.  40.  67.]
 [121. 121.   0.  55. 121.]
 [  0.   0.   0.   0.   0.]
 [  5. 121.   0.   0.  75.]
 [ 27.  27.  23.  25.   0.]
 [  0.  37.   0.  49.   0.]
 [  0. 119. 121. 115.  14.]
 [  0.  59.  32. 100.  63.]
 [  0.   0.   0.   0.   0.]
 [ 69.  84.  69.  69.  71.]
 [  0.   0.   0.   0.   0.]
 [121. 117. 121.   0. 121.]
 [ 46.   0.   0.   0.   0.]
 [ 62.   0. 121.  41.   0.]
 [121. 121.   0. 121.   0.]
 [121. 121. 105. 118. 103.]
 [ 25. 121. 121. 106. 121.]
 [  0.   0.   0.   5.   0.]
 [ 18.  25.  23.  37.  22.]
 [  0.   0.   0.   0

In [18]:
print(pyl_recovery[0])

[121.   0. 121. 121. 121.]


In [20]:
contains_bad = np.unique(np.where(pyl_recovery==0)[0])
contains_good = np.unique(np.where(pyl_recovery==121)[0])
contains_mixed = np.unique(np.where((pyl_recovery>2)&(pyl_recovery<120))[0])
contains_goodmixed = np.intersect1d(contains_good,contains_mixed)
contains_all = np.intersect1d(np.intersect1d(contains_bad,contains_good),contains_mixed)

In [22]:
print(contains_all)

[ 5 14 17 19 22 27 29 46 50 51 52 53 54 55 57 61 72 73 78 79 83 87 89 92
 96]


In [24]:
print(contains_all)
print(pyl_recovery[contains_all[:-1]])

[ 5 14 17 19 22 27 29 46 50 51 52 53 54 55 57 61 72 73 78 79 83 87 89 92
 96]
[[121. 113.   0. 121. 121.]
 [121. 121.  99.   0.  86.]
 [121. 121.   0.  55. 121.]
 [  5. 121.   0.   0.  75.]
 [  0. 119. 121. 115.  14.]
 [121. 117. 121.   0. 121.]
 [ 62.   0. 121.  41.   0.]
 [121.  59. 110.   0.  55.]
 [ 32. 121.   0.   0.  72.]
 [ 47. 110.   0. 121.   0.]
 [  1. 121. 121. 110.   0.]
 [121.   0.   0.  29. 121.]
 [ 99. 121.  45. 110.   0.]
 [  0.   0. 121.   0.  47.]
 [ 46. 110.   0. 121.  39.]
 [  0. 121.   7.   8.   0.]
 [121.  62.   0. 121.   0.]
 [108. 110. 121. 121.   0.]
 [ 55.   0. 121.  54. 119.]
 [121.   0.   0.  55. 121.]
 [ 67. 106.   0. 107. 121.]
 [ 85. 121.  95.  38.   0.]
 [110. 121.  40.   0. 110.]
 [  0. 121. 121.  78. 121.]]


In [ ]:
# lots and lots of ICs contain possible long-timescale cycles. 
# It's possible that these are just the result of passing through the pyloric zone, and trajectories
# do not actually keep returning to the same place...
# In any case, this behavior would be considered similar to the "bouting" that is observed in
# homeostatically recovering STG preparations
contains_bout = []
for i in range(100):
    for j in range(5):
        for ic in range(121):
            switch1 = False
            switch2 = False
            for k in range(10-1):
                if ((recovery[i,j,ic,k]<.3) != (recovery[i,j,ic,k+1]<.3)):
                    if switch1:
                        switch2=True
                        break
                    switch1 = True
            if switch2:
                contains_bout.append([i,j,ic])
                break
contains_bout = np.array(contains_bout)
# print(contains_bout)