In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
recovery = np.zeros((100,5,121,5))
final_recovery = np.zeros_like(recovery[:,:,:,0])
pyl_recovery = np.zeros((100,5))
for i in range(100):
    for j in range(5):
        # print(np.loadtxt("./Specifically Evolved HP mechanisms/Every Circuit/%s/%s/recoverytest.dat"%(i,j))[:,2:])
        recovery[i,j] = np.loadtxt("./Specifically Evolved HP mechanisms/Every Circuit/%s/%s/recoverytest.dat"%(i,j))[:,2:]
        final_recovery[i,j] = recovery[i,j,:,-1]
        pyl_recovery[i,j] = np.sum(final_recovery[i,j]>=.3)


In [ ]:
#repeat but with the zero-range HPmetaparameter plane
recovery = np.zeros((100,5,121,5))
final_recovery = np.zeros_like(recovery[:,:,:,0])
pyl_recovery = np.zeros((100,5))
for i in range(100):
    for j in range(5):
        # print(np.loadtxt("./Specifically Evolved HP mechanisms/Every Circuit/%s/%s/recoverytest.dat"%(i,j))[:,2:])
        recovery[i,j] = np.loadtxt("./Specifically Evolved HP mechanisms/Every Circuit/%s/%s/recoverytest.dat"%(i,j))[:,2:]
        final_recovery[i,j] = recovery[i,j,:,-1]
        pyl_recovery[i,j] = np.sum(final_recovery[i,j]>=.3)

In [4]:
print(pyl_recovery)

[[121.  77. 121. 121. 121.]
 [121. 121. 121. 121. 121.]
 [  0.   0.   0.   0.   0.]
 [121. 121. 121. 121. 121.]
 [121. 121. 121. 121. 121.]
 [121. 121. 121. 121. 121.]
 [ 77.   0.   0.   0.  78.]
 [121. 121. 121. 121. 121.]
 [ 64.  98.  89.  99. 121.]
 [  0.   0.  46.   0.   0.]
 [121. 121. 121. 121. 121.]
 [  0.   0.   0.   0.   0.]
 [110. 110. 121. 110. 110.]
 [121. 121. 121. 121. 121.]
 [121. 121. 121. 121. 121.]
 [  0.  18.   0.   0.   0.]
 [ 84.  87. 112.  91.  98.]
 [121. 121. 121. 121. 121.]
 [  0.   0.   0.   0.   0.]
 [121. 121. 121. 121. 121.]
 [  0.   0.   0.   0.   0.]
 [121.  59.  58. 121. 121.]
 [121. 121. 121.   0. 121.]
 [121. 121.   0. 121.  88.]
 [  0.   0.   0.   0.   0.]
 [121.   0. 121. 121. 121.]
 [ 24.   0.   0.   0.   0.]
 [121. 121. 121.  57.  66.]
 [  1.   0.   0.   0.   0.]
 [  0.   0.   0.  21.  59.]
 [121. 121. 121. 121. 121.]
 [121. 121.  10.  50. 121.]
 [121. 121. 121. 121. 121.]
 [121. 121. 121. 121. 121.]
 [ 17.  14.  19.  22.   0.]
 [121. 121. 121. 121

In [15]:
contains_bad = np.unique(np.where(pyl_recovery==0)[0])
contains_good = np.unique(np.where(pyl_recovery==121)[0])
contains_mixed = np.unique(np.where((pyl_recovery>2)&(pyl_recovery<120))[0])
contains_goodmixed = np.intersect1d(contains_good,contains_mixed)
contains_all = np.intersect1d(np.intersect1d(contains_bad,contains_good),contains_mixed)
unsolvable = np.setdiff1d(np.arange(0,100).astype(int),contains_good)

In [16]:
print(contains_all)
print(pyl_recovery[contains_all])
print(unsolvable)
print(pyl_recovery[unsolvable])

[23 40 50 74 87]
[[121. 121.   0. 121.  88.]
 [121. 103.   0. 121.  71.]
 [121. 121. 121.  26.   0.]
 [  0.   0. 115.  29. 121.]
 [ 61.   0. 121.  31.  23.]]
[ 2  6  9 11 15 16 18 20 24 26 28 29 34 36 39 44 48 59 64 69 70 75 76 78
 80 81 82 85 90 95]
[[  0.   0.   0.   0.   0.]
 [ 77.   0.   0.   0.  78.]
 [  0.   0.  46.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.  18.   0.   0.   0.]
 [ 84.  87. 112.  91.  98.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ 24.   0.   0.   0.   0.]
 [  1.   0.   0.   0.   0.]
 [  0.   0.   0.  21.  59.]
 [ 17.  14.  19.  22.   0.]
 [ 42.  59.  90.  67.  41.]
 [ 56.  64.  56.  46.  40.]
 [  0.   0.   0.   0.   0.]
 [ 38.  51.  10.  36.  39.]
 [ 51.  11.   2.  97.  12.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ 48.  15.  36.  12.   0.]
 [  0.   0.   0.   0.   0.]
 [ 11.  17.   4.   2.   6.]
 [119. 120. 120.  46.  60.]
 [ 41.   0.   3.  30.  33.]
 [  0.   0.  22.   0.   0.]
 [100. 119. 114. 119.

In [ ]:
# lots and lots of ICs contain possible long-timescale cycles. 
# It's possible that these are just the result of passing through the pyloric zone, and trajectories
# do not actually keep returning to the same place...
# In any case, this behavior would be considered similar to the "bouting" that is observed in
# homeostatically recovering STG preparations
contains_bout = []
for i in range(100):
    for j in range(5):
        for ic in range(121):
            switch1 = False
            switch2 = False
            for k in range(10-1):
                if ((recovery[i,j,ic,k]<.3) != (recovery[i,j,ic,k+1]<.3)):
                    if switch1:
                        switch2=True
                        break
                    switch1 = True
            if switch2:
                contains_bout.append([i,j,ic])
                break
contains_bout = np.array(contains_bout)
# print(contains_bout)

In [11]:
recovery_classifications = np.loadtxt('./solvability_readable_smallertol.txt')
recovery_classifications[:,3] = recovery_classifications[:,3]/121
recovery_classifications[:,4] = recovery_classifications[:,4]/25

In [12]:
print("theory fails:")
for i in range(100):
    if (recovery_classifications[i,2] != (recovery_classifications[i,4]==1)):
        print(recovery_classifications[i].round(3))
print("theory succeeds:")
for i in range(100):
    if (recovery_classifications[i,2] == (recovery_classifications[i,4]==1)):
        print(recovery_classifications[i])

theory fails:
[11.  0.  0.  0.  1.]
[15.     0.     0.     0.149  1.   ]
[24.    1.    1.    0.    0.56]
[59.     0.     0.     0.802  1.   ]
[69.    1.    1.    0.    0.96]
[70.     0.     0.     0.397  1.   ]
[90.     1.     1.     0.554  0.48 ]
theory succeeds:
[0. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[2.  0.  0.  0.  0.8]
[3. 1. 1. 1. 1.]
[4. 1. 1. 1. 1.]
[5. 1. 1. 1. 1.]
[6.        1.        1.        0.6446281 1.       ]
[7. 1. 1. 1. 1.]
[8. 1. 1. 1. 1.]
[9.         0.         0.         0.38016529 0.52      ]
[10.  1.  1.  1.  1.]
[12.  1.  1.  1.  1.]
[13.  1.  1.  1.  1.]
[14.  1.  1.  1.  1.]
[16.          1.          0.          0.92561983  0.8       ]
[17.  1.  1.  1.  1.]
[18.    0.    0.    0.    0.36]
[19.  1.  1.  1.  1.]
[20.   0.   0.   0.   0.6]
[21.  1.  1.  1.  1.]
[22.  1.  1.  1.  1.]
[23.  1.  1.  1.  1.]
[25.  1.  1.  1.  1.]
[26.          0.          0.          0.19834711  0.72      ]
[27.  1.  1.  1.  1.]
[2.80000000e+01 0.00000000e+00 0.00000000e+00 8.26446281e-03