In [4]:
import numpy as np

In [8]:
startendidxs = np.arange(6,12)
test = np.delete(startendidxs,3)
print(test)
print(startendidxs)

[ 6  7  8 10 11]
[ 6  7  8  9 10 11]


In [ ]:
#all possible combinations of start and end
startendset = ["LPstart","LPend","PYstart","PYend","PDstart","PDend"]
startendidxs = np.arange(6)

allcombos = np.zeros((720,6))
idx = 0

for a in range(6):
    arr1 = np.delete(startendidxs,a)
    for b in range(5):
        arr2 = np.delete(arr1,b)
        for c in range(4):
            arr3 = np.delete(arr2,c)
            for d in range(3):
                arr4 = np.delete(arr3,d)
                for e in range(2):
                    arr5 = np.delete(arr4,e)
                    allcombos[idx] = [startendidxs[a],arr1[b],arr2[c],arr3[d],arr4[e],arr5[0]]
                    idx += 1

In [ ]:
#do we have to eliminate any impossibilities? i don't think so because you can have an end before a start (matter of perspective)

#we could eliminate repeats  which are equivalent to each other up to wrap around
nonequivalentcombos = np.zeros((720,6))

for i in range(len(allcombos)):
    for j in range(6):
        if allcombos[i,j] != 4: #starting at the PDstart (important to follow Prinz paper convention)
            continue
        else:
            test = np.zeros(6)
            for k in range(6):
                test[k] = allcombos[i,(j+k)%6]
            print(allcombos[i],test)
            nonequivalentcombos[i] = test

nonequivalentcombos = np.unique(nonequivalentcombos,axis=0)
print(len(nonequivalentcombos))
#probably is something with 5!... oh well won't think about it 

[0. 1. 2. 3. 4. 5.] [4. 5. 0. 1. 2. 3.]
[0. 1. 2. 3. 5. 4.] [4. 0. 1. 2. 3. 5.]
[0. 1. 2. 4. 3. 5.] [4. 3. 5. 0. 1. 2.]
[0. 1. 2. 4. 5. 3.] [4. 5. 3. 0. 1. 2.]
[0. 1. 2. 5. 3. 4.] [4. 0. 1. 2. 5. 3.]
[0. 1. 2. 5. 4. 3.] [4. 3. 0. 1. 2. 5.]
[0. 1. 3. 2. 4. 5.] [4. 5. 0. 1. 3. 2.]
[0. 1. 3. 2. 5. 4.] [4. 0. 1. 3. 2. 5.]
[0. 1. 3. 4. 2. 5.] [4. 2. 5. 0. 1. 3.]
[0. 1. 3. 4. 5. 2.] [4. 5. 2. 0. 1. 3.]
[0. 1. 3. 5. 2. 4.] [4. 0. 1. 3. 5. 2.]
[0. 1. 3. 5. 4. 2.] [4. 2. 0. 1. 3. 5.]
[0. 1. 4. 2. 3. 5.] [4. 2. 3. 5. 0. 1.]
[0. 1. 4. 2. 5. 3.] [4. 2. 5. 3. 0. 1.]
[0. 1. 4. 3. 2. 5.] [4. 3. 2. 5. 0. 1.]
[0. 1. 4. 3. 5. 2.] [4. 3. 5. 2. 0. 1.]
[0. 1. 4. 5. 2. 3.] [4. 5. 2. 3. 0. 1.]
[0. 1. 4. 5. 3. 2.] [4. 5. 3. 2. 0. 1.]
[0. 1. 5. 2. 3. 4.] [4. 0. 1. 5. 2. 3.]
[0. 1. 5. 2. 4. 3.] [4. 3. 0. 1. 5. 2.]
[0. 1. 5. 3. 2. 4.] [4. 0. 1. 5. 3. 2.]
[0. 1. 5. 3. 4. 2.] [4. 2. 0. 1. 5. 3.]
[0. 1. 5. 4. 2. 3.] [4. 2. 3. 0. 1. 5.]
[0. 1. 5. 4. 3. 2.] [4. 3. 2. 0. 1. 5.]
[0. 2. 1. 3. 4. 5.] [4. 5. 0. 2. 1. 3.]


In [ ]:
np.where((nonequivalentcombos == (5).all(axis=1)))

Really, the criteria are not specific enough to deal with this conception. I'd need to know what the actual biology is behind these choices. Is it important that there is an actual gap?

In [33]:
criteria = np.zeros((120,3))
for i in range(len(nonequivalentcombos)):
    if np.where(nonequivalentcombos[i]==0)[0]<np.where(nonequivalentcombos[i]==2)[0]: #LPstart<PYstart
        criteria[i,0] = 1
    if np.where(nonequivalentcombos[i]==1)[0]<np.where(nonequivalentcombos[i]==3)[0]: #LPend<PYend
        criteria[i,1] = 1
    if np.where(nonequivalentcombos[i]==5)[0]<np.where(nonequivalentcombos[i]==0)[0]: #PDend < LPstart
        criteria[i,2] = 1
print(criteria)
print("no criteria met:",np.where((criteria == (0, 0, 0)).all(axis=1))[0])
print("pyloric:",np.where((criteria == (1, 1, 1)).all(axis=1))[0])
print(nonequivalentcombos[np.where((criteria == (1, 1, 1)).all(axis=1))[0]])

[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [0.